module.exports = {
  ZONES: {
    CORE: 'CORE',
    BUFFER: 'BUFFER',
    VILLAGE_ADJACENT: 'VILLAGE_ADJACENT'
  },
  
  ROLES: {
    ADMIN: 'admin',
    FIELD_BIOLOGIST: 'biologist',
    RANGE_OFFICER: 'range_officer',
    REVIEWER: 'reviewer'
  },

  ALERT_TYPES: {
    RANGE_CENTROID_SHIFT: 'RANGE_CENTROID_SHIFT',
    FIRST_STATION_CAPTURE: 'FIRST_STATION_CAPTURE',
    BUFFER_ENCROACHMENT: 'BUFFER_ENCROACHMENT',
    VILLAGE_ADJACENT_RISK: 'VILLAGE_ADJACENT_RISK',
    PROLONGED_ABSENCE: 'PROLONGED_ABSENCE'
  },

  ALERT_SEVERITY: {
    CRITICAL: 'CRITICAL',
    WARNING: 'WARNING',
    INFO: 'INFO'
  },

  THRESHOLDS: {
    CORE_CENTROID_SHIFT_KM2: 17.5,
    BUFFER_CENTROID_SHIFT_KM: 5.0,
    VILLAGE_ADJACENT_ALERT_KM: 2.5,
    PROLONGED_ABSENCE_DAYS: 45,
    AI_HIGH_THRESHOLD: 0.82,
    AI_LOW_THRESHOLD: 0.65,
    AI_BLANK_THRESHOLD: 0.85
  },

  PENCH_CENTER: {
    lat: 21.6950,
    lon: 79.3500
  }
};
